### ISSUE TITLE
errors building boost for c++11

### ISSUE THREAD

**Issue by daveyostcom** [hnrkptrsn/FeedBack#1]
I'm trying to build boost to be used when compiling with -lang=c++11

I'm on fedora 17.
The binary clang distribution (unchanged) is in /usr/local/llvm/3.4/
and that is first in my path.

When I run your b2 that builds boost, I get a lot of stuff that looks fatal, like this:

```
clang-linux.compile.c++.without-pth bin.v2/libs/regex/build/clang-linux-3.4/release/threading-multi/c_regex_traits.o
In file included from libs/regex/build/../src/c_regex_traits.cpp:22:
In file included from ./boost/config.hpp:40:
./boost/config/select_stdlib_config.hpp:18:12: fatal error: 'cstddef' file not found
#  include <cstddef>
           ^
1 error generated.
```

Any idea why this might be happening?

Thanks

**Comment by hnrkptrsn** [comment]
I see you are using clang 3.4 - any chance you didn't install libc++? (possibly write a small test program just using c++ and a libc++ feature to verify that you got libc++ installed)

Which version of Boost are you using? I believe I used 1.53 when I wrote the post and now I'm on 1.54.  

Another option, which I know is not exactly solving your particular problem, would be to only compile the libs you need or perhaps exclude some you definitely won't need.  

--with-libraries=library-name-list or --without--libraries=library-name-list

Have a look at 5.2.4:
http://www.boost.org/doc/libs/1_55_0/more/getting_started/unix-variants.html
